name: eobox
channels:
- conda-forge
- defaults
dependencies:
- affine
- descartes
- cython
- libgdal
- gdal
- geopandas
- matplotlib
- pandas
- pip
- python=3.6 
- pytest>=3.6.0
- numpy
- rasterio
- seaborn
- tqdm
- scikit-learn
- sphinx>=1.8
- twine
- nbsphinx
- ipython
- jupyter
- pip:
  - sphinx-rtd-theme