name: _eotools
channels:
- conda-forge
- defaults
dependencies:
- python>=3.5
- cython
- libgdal
- gdal
- pandas
- numpy
- rasterio
- pip:
  - Sphinx
  - sphinx-rtd-theme
  - nbsphinx
  - ipython
  - m2r
