name: _eotools
channels:
- conda-forge
- defaults
dependencies:
- python>=3.5
- cython
- libgdal
- gdal
- geopandas
- matplotlib
- pandas
- numpy
- rasterio
- seaborn
- tqdm
- pip:
  - sphinx>=1.8
  - sphinx-rtd-theme
  - nbsphinx
  - ipython
