name: _eotools
channels:
- conda-forge
- defaults
dependencies:
- python>=3.5
- cython
- libgdal
- gdal
- pandas
- numpy
- rasterio
- pip:
  - sphinx>=1.8
  - sphinx-rtd-theme
  - nbsphinx
  - ipython
